repos:
-  repo: local
   hooks:
   -  id: black
      name: black
      language: system
      entry: black --check -q
      types: [python]
   -  id: golangci
      name: golangci
      language: system
      entry: golangci-lint run
      pass_filenames: false
      types: [go]
   -  id: isort
      name: isort
      language: system
      entry: isort --check
      types: [python]
   -  id: revive
      name: revive
      language: system
      entry: revive -exclude ./vendor/... ./...
      pass_filenames: false
      types: [go]
   -  id: vet
      name: go vet
      language: system
      entry: go vet -tags integration ./...
      pass_filenames: false
      types: [go]
   -  id: terraform
      name: terraform
      language: system
      entry: terraform fmt -check -recursive terraform/
      pass_filenames: false
      types: [terraform]
